### ISSUE TITLE
Human genome in function for GSEA And AIRR_to_VGM trim.and.align = T load error

### ISSUE THREAD

**Issue by leeanapeters** [alexyermanos/Platypus#9]
Hi there, just wanted to point out that the "species" argument doesn't seem to work for anything other than mouse in the GEX_GO_TERM function unless you modify the function to have org.hs.eg.db listed instead of the mouse genome! Didn't see it listed in the vignette so wanted to point that out for people working with human data.

Thanks for the great package!

Leeana

**Comment by vickreiner** [comment]
Thanks for pointing this out! 
We will fix this and push and update as soon as possible!

**Comment by leeanapeters** [comment]
No problem, thanks for the quick response! 

Another unrelated question (happy to post separately) but are you all thinking of including the output of TRUST4 (at least for BCR)? I am noticing just the CSV does not work even after conversion to 10x format.

**Comment by leeanapeters** [comment]
Hi @vickreiner, thank you for the help with this! I am encountering an error and am not sure if it is the one you mentioned. It happens with only one sample so I hope it is not a case of large output. 
[1] "2022-02-10 20:45:33 EST"
[1] "2022-02-10 20:45:33 EST"
[1] "2022-02-10 20:50:55 EST"
Error in substr(curr.barcode$VDJ_sequence_nt_raw, as.numeric(curr.contigs$v_sequence_start[1]),  : 
  invalid substring arguments

This is after I've run 

VgmTB<- PlatypusDB_AIRR_to_VGM(AIRR.input =TBlist, group.id = c("T1D", "T1D", "CTL", "CTL"),
                                VDJ.combine = FALSE, trim.and.align = TRUE, filter.overlapping.barcodes.VDJ = FALSE)


I've made lists of the paths to the tsvs or lists of tables of the tsvs loaded into the R environment and get the error either way.


Any help would be much appreciated! And happy to move to a different issue if you'd like to close the GSEA one :)

Thanks

**Comment by vickreiner** [comment]
Hi Leeana, 

this issue stems from the information needed for sequence trimming. 
Airr.tsv tables from Cellranger come with a couple of numeric columns that indicate the start and end index of a given gene segment (e.g. v_sequence_start, v_sequence_end). TRUST4 does not seem to output any such columns, which is why the function fails. 
I pushed a new version that issues a warning to the user in this case rather than failing. 

Despite this it is still possible to get the trimmed sequence from TRUST4 via MiXCR alignment (which is a little ironic, given that the two are basically competitors). 
You can use the Platypus_AIRR_to_VGM function with trim.and.align = FALSE 

`VgmTB<- PlatypusDB_AIRR_to_VGM(AIRR.input =TBlist, group.id = c("T1D", "T1D", "CTL", "CTL"),
VDJ.combine = FALSE, trim.and.align = FALSE, filter.overlapping.barcodes.VDJ = FALSE)`

and then use the VDJ_call_MIXCR function (see documentation of that for info on how to download MiXCR so that R can access it) to realign and output nucleotide sequences of all Framework and CDR regions. Once pasted together, these yield a full variable region contig. 

`VgmTB[[1]][[1]]  <- VDJ_call_MIXCR(VDJ = VgmTB[[1]][[1]], platypus.version = "v3")`
(Nested list indexing here, because the PlatypusDB_AIRR_to_VGM function returns a list of VDJ dataframes if VDJ.combine = FALSE. I would always recommend setting VDJ.combine to TRUE for convenience.) 

Hope this helps! 
Best,
Victor

**Comment by vickreiner** [comment]
I pushed a fix to the GEX_GOterm function to ensure that it works with human data as well. 
Let me know if any issues persist. 

https://github.com/alexyermanos/Platypus/blob/master/R/GEX_GOterm.R

Best,
Victor

**Comment by leeanapeters** [comment]
Hey Victor, thank you for the help!

Hopefully last question about the AIRR format and MIXCR.

I made sure to have the mixcr.jar file in my working directory, but I am getting an error.

 VgmTB[[1]]<- VDJ_call_MIXCR(VDJ = VgmTB[[1]], mixcr.directory = "G:/BRUSKO_LAB/SINGLE-CELL_DATA_ARCHIVE/NS1998/out/count/sct objects/mixcr.jar",platypus.version = "v3", species = "hsa", simplify = TRUE)
Windows system detected
Microsoft Windows [Version 10.0.18363.2037]
(c) 2019 Microsoft Corporation. All rights reserved.

G:\BRUSKO_LAB\SINGLE-CELL_DATA_ARCHIVE\NS1998\out\count\sct objects>Microsoft Windows [Version 10.0.18363.2037]
(c) 2019 Microsoft Corporation. All rights reserved.

G:\BRUSKO_LAB\SINGLE-CELL_DATA_ARCHIVE\NS1998\out\count\sct objects>Microsoft Windows [Version 10.0.18363.2037]
(c) 2019 Microsoft Corporation. All rights reserved.

G:\BRUSKO_LAB\SINGLE-CELL_DATA_ARCHIVE\NS1998\out\count\sct objects>Microsoft Windows [Version 10.0.18363.2037]
(c) 2019 Microsoft Corporation. All rights reserved.

G:\BRUSKO_LAB\SINGLE-CELL_DATA_ARCHIVE\NS1998\out\count\sct objects>Microsoft Windows [Version 10.0.18363.2037]
(c) 2019 Microsoft Corporation. All rights reserved.

G:\BRUSKO_LAB\SINGLE-CELL_DATA_ARCHIVE\NS1998\out\count\sct objects>Microsoft Windows [Version 10.0.18363.2037]
(c) 2019 Microsoft Corporation. All rights reserved.

G:\BRUSKO_LAB\SINGLE-CELL_DATA_ARCHIVE\NS1998\out\count\sct objects>Microsoft Windows [Version 10.0.18363.2037]
(c) 2019 Microsoft Corporation. All rights reserved.

G:\BRUSKO_LAB\SINGLE-CELL_DATA_ARCHIVE\NS1998\out\count\sct objects>Microsoft Windows [Version 10.0.18363.2037]
(c) 2019 Microsoft Corporation. All rights reserved.

G:\BRUSKO_LAB\SINGLE-CELL_DATA_ARCHIVE\NS1998\out\count\sct objects>Microsoft Windows [Version 10.0.18363.2037]
(c) 2019 Microsoft Corporation. All rights reserved.

G:\BRUSKO_LAB\SINGLE-CELL_DATA_ARCHIVE\NS1998\out\count\sct objects>Microsoft Windows [Version 10.0.18363.2037]
(c) 2019 Microsoft Corporation. All rights reserved.

G:\BRUSKO_LAB\SINGLE-CELL_DATA_ARCHIVE\NS1998\out\count\sct objects>Microsoft Windows [Version 10.0.18363.2037]
(c) 2019 Microsoft Corporation. All rights reserved.

G:\BRUSKO_LAB\SINGLE-CELL_DATA_ARCHIVE\NS1998\out\count\sct objects>Microsoft Windows [Version 10.0.18363.2037]
(c) 2019 Microsoft Corporation. All rights reserved.

G:\BRUSKO_LAB\SINGLE-CELL_DATA_ARCHIVE\NS1998\out\count\sct objects>Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :

 Error in file(file, "rt") : cannot open the connection

Do you have any recommendations?


Thanks again,

Leeana
________________________________

**Comment by vickreiner** [comment]
Hi, 

that looks like R did not find MiXCR at the expected location. 
When specifying the MiXCR directory, please do not include the actual /mixcr.jar file in the path. Alternatively you can not specify this directory and R will just use the current working directory as default.  

`VgmTB[[1]]<- VDJ_call_MIXCR(VDJ = VgmTB[[1]],platypus.version = "v3", species = "hsa", simplify = TRUE)`

Sorry that for the complication. I will specify this further in the documentation and add an error catcher for this. 

Best, 
Victor!

**Comment by leeanapeters** [comment]
Sorry I should have mentioned that I tried without the path specified and with the path leading to mixcr.jar but not including the actual file and I still receive the error.
________________________________

**Comment by leeanapeters** [comment]
Here is the traceback in case it is helpful!

 Error in file(file, "rt") : cannot open the connection
3.
file(file, "rt")
2.
utils::read.table(file = "tempmixcrhc.out.txt", sep = "\t", header = T,
    stringsAsFactors = FALSE, fill = TRUE)
1.
VDJ_call_MIXCR(VDJ = VgmTB[[1]], platypus.version = "v3", species = "hsa",
    simplify = TRUE)
________________________________

**Comment by vickreiner** [comment]
Thanks for the error trace. This is R complaining that I did not find a MiXCR output. Given your previous output that just means that MiXCR did not run. 
Can you open your CMD and navigate to the directory where mixcr.jar is located
`cd "G:\[add full path here]\sct objects"`
if that works, try starting mixcr using: 
`java -jar mixcr.jar`
If that returns the mixcr documentation and no error, than mixcr is able to run properly.

**Comment by mourisl** [comment]
Hi, TRUST4's developer here. Leeana opened an issue in TRUST4, and I tracked the leads to here :). 

The v_sequence_start, v_sequence_end information is optional in AIRR specification, so I did not output that information to keep the output minimal. 
But the sequence trimming information can be read out in the mandatory v_cigar, j_cigar field in the AIRR format. I think the value of the first soft clipping symbol in v_cigar plus 1 corresponds to the v_sequence_start number. For j_sequence_end, it can be read from the j_cigar string last soft clipping symbol, and then (the sequence length - the last soft clipping number) will be j_sequence_end. Hope this helps.

**Comment by vickreiner** [comment]
Hi,
Thanks for getting in touch! 
That sounds great. I will check back with the AIRR guidelines too and implement this into Platypus.

Also thanks for TRUST4 as a whole. I have been testing it out on a couple of published datasets and so far I am very impressed!

**Comment by vickreiner** [comment]
Added @mourisl suggestions to Platypus_AIRR_to_VGM(). 
Trim.and.align = T now works also with TRUST4 input

**Comment by leeanapeters** [comment]
Hi Victor, thanks for the updates!

I am still encountering the error for accessing mixcr in R even though I can get mixcr to run in the same directory thru the terminal. Sorry for pestering you! Do you know of any way I can get around this? 

 Error in file(file, "rt") : cannot open the connection 
3.
file(file, "rt") 
2.
utils::read.table(file = "tempmixcrhc.out.txt", sep = "\t", header = T, 
    stringsAsFactors = FALSE, fill = TRUE) 
1.
VDJ_call_MIXCR(VDJ = VgmTB[[1]], platypus.version = "v3", species = "hsa", 
    simplify = TRUE)

**Comment by vickreiner** [comment]
Hi Leeana, 
sorry for the very late reply. 
Have you tried this possibly on another machine?

**Comment by MaryGoAround** [comment]
Hi

I need help please

I have two PBMCs

I have 10x 5' GEX, TCR, BCR data for that on which I run TRUST4 and I am using `TRUST_barcode_airr.tsv` files as an input

I noticed for each kit separately (TCR or BCR not both) I can run the code but having the data together returns error

```
>   VDJ.out.directory.list <- list()
  >   VDJ.out.directory.list_T[[1]] <- c("/data/TRUST4-master/TRUST_PN0340_0001_TCR_S1_L001_R2_001_barcode_airr.tsv") # sample1
  >   VDJ.out.directory.list_T[[2]] <- c("/data/TRUST4-master/TRUST_PN0340_0002_TCR_S4_L001_R2_001_barcode_airr.tsv") # sample2
  >   VDJ.out.directory.list_B[[1]] <- c("/data/TRUST4-master/TRUST_PN0340_0001_BCR_S2_L001_R2_001_barcode_airr.tsv") # sample1
  Error in VDJ.out.directory.list_B[[1]] <- c("/data/TRUST4-master/TRUST_PN0340_0001_BCR_S2_L001_R2_001_barcode_airr.tsv") : 
    object 'VDJ.out.directory.list_B' not found
  >   VDJ.out.directory.list_B[[2]] <- c("/data/TRUST4-master/TRUST_PN0340_0002_BCR_S5_L001_R2_001_barcode_airr.tsv") # sample2
  Error in VDJ.out.directory.list_B[[2]] <- c("/data/TRUST4-master/TRUST_PN0340_0002_BCR_S5_L001_R2_001_barcode_airr.tsv") : 
    object 'VDJ.out.directory.list_B' not found
  >   VDJ.out.directory.list_GEX[[1]] <- c("/data/TRUST4-master/TRUST_PN0340_0001_GEX_S3_L001_R2_001_barcode_airr.tsv") # sample1
  Error in VDJ.out.directory.list_GEX[[1]] <- c("/data/TRUST4-master/TRUST_PN0340_0001_GEX_S3_L001_R2_001_barcode_airr.tsv") : 
    object 'VDJ.out.directory.list_GEX' not found
  >   VDJ.out.directory.list_GEX[[2]] <- c("/data/TRUST4-master/TRUST_PN0340_0002_GEX_S6_L001_R2_001_barcode_airr.tsv") # sample2
  Error in VDJ.out.directory.list_GEX[[2]] <- c("/data/TRUST4-master/TRUST_PN0340_0002_GEX_S6_L001_R2_001_barcode_airr.tsv") : 
    object 'VDJ.out.directory.list_GEX' not found
```
But for one kit that works

```
VDJ.out.directory.list_T <- list()
  >   VDJ.out.directory.list_T[[1]] <- c("/data/TRUST4-master/TRUST_PN0340_0001_TCR_S1_L001_R2_001_barcode_airr.tsv") # sample1
  >   VDJ.out.directory.list_T[[2]] <- c("/data/TRUST4-master/TRUST_PN0340_0002_TCR_S4_L001_R2_001_barcode_airr.tsv") # sample2
  >   VgmT<- PlatypusDB_AIRR_to_VGM(AIRR.input =VDJ.out.directory.list_T, group.id = c("tcr1", "tcr2"), VDJ.combine = FALSE, trim.and.align = FALSE, filter.overlapping.barcodes.VDJ = FALSE)
  > VgmT
  $VDJ
  $VDJ[[1]]
  orig_barcode             barcode sample_id group_id clonotype_id celltype Nr_of_VDJ_chains Nr_of_VJ_chains
  1  AAAAAAACAGAATTTC s1_AAAAAAACAGAATTTC        s1     bcr1 Undetermined   T cell                1               0
  2  AAAAAACCAACGAACC s1_AAAAAACCAACGAACC        s1     bcr1 Undetermined   T cell                0               1
  3  AAAAAACTATACCATC s1_AAAAAACTATACCATC        s1     bcr1 Undetermined   T cell                0               1
  4  AAAAAATTCAACCACT s1_AAAAAATTCAACCACT        s1     bcr1 Undetermined   T cell                1               0
```

Any idea please? Shall I make one separate object for each kit? Then how to merge that?

Thanks for any idea
